### ISSUE TITLE
This may be if (userRewards_.checkpoint == rewardsPerToken_.accumulated)

### ISSUE THREAD

**Issue by fenglingooooooh** [alcueca/Staking#1]
https://github.com/alcueca/staking/blob/b9349f3af585c03121c3627a57e0d4312c913c14/src/SimpleRewards.sol#L105C57-L105C68

**Comment by alcueca** [comment]
Fixed, thank you.

https://github.com/alcueca/staking/commit/fa16a77e9a4549330bad3f1874489af2c1b22de7
